# Generated by Django 5.2 on 2025-05-26 15:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_updated_at_alter_project_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='ended_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='github',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stacks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Tech Stacks'),
        ),
    ]
