# Generated by Django 5.2 on 2025-05-28 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_end_date_project_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Tech Stacks'),
        ),
    ]
