# Generated by Django 5.2 on 2025-05-28 14:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Features'),
        ),
    ]
