# Generated by Django 5.2 on 2026-01-08 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='case_study',
            field=models.TextField(blank=True, verbose_name='Case Study'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Featured Image Public ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Featured Image URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='default', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_url',
            field=models.URLField(default=None, verbose_name='Image URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectimage',
            name='public_id',
            field=models.CharField(default=None, max_length=255, verbose_name='Cloudinary Public ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('web', 'Web Development'), ('software', 'Software'), ('other', 'Other')], default='other', max_length=20, verbose_name='Project Type'),
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(help_text='e.g., github, live, demo, other', max_length=50, verbose_name='Link Type')),
                ('label', models.CharField(max_length=100, verbose_name='Link Label')),
                ('url', models.URLField(verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Link',
                'verbose_name_plural': 'Project Links',
                'ordering': ['created_at'],
            },
        ),
    ]
