# Generated by Django 5.2 on 2026-01-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectimage_options_remove_project_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
