services:
  redis:
    image: redis:7-alpine
    container_name: medusa-redis
    ports:
      - "6380:6379"
    networks:
      - medusa-network
    restart: unless-stopped

  medusa_app:
    image: medusa-app
    container_name: medusa-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: unless-stopped
    command: >
      bash -c "pip install uvicorn[standard] celery[redis] && \
      uvicorn medusa.asgi:application --host 0.0.0.0 --port 5000 --reload"
    networks:
      - medusa-network

  celery_worker:
    image: medusa-app
    container_name: medusa-celery-worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - redis
      - medusa_app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A medusa worker --loglevel=info
    networks:
      - medusa-network
    restart: unless-stopped

  celery_beat:
    image: medusa-app
    container_name: medusa-celery-beat
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - redis
      - medusa_app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A medusa beat --loglevel=info
    networks:
      - medusa-network
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:

networks:
  medusa-network:
    external: true