version: '3.9'

services:
  web:
    container_name: medusa_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    restart: always
    networks:
      - medusa_network

networks:
  medusa_network:
    external: true
