version: '3.9'

services:
  medusa_app:
    container_name: medusa_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - medusa_db
      - medusa_redis
    networks:
      - medusa-network

  medusa_db:
    image: postgres:16
    container_name: medusa_postgres
    environment:
      - POSTGRES_DB=${PGDB_NAME}
      - POSTGRES_USER=${PGDB_USER}
      - POSTGRES_PASSWORD=${PGDB_PASSWORD}
    volumes:
      - medusa_data:/var/lib/postgresql/data/
    ports:
      - "5440:5432"
    networks:
      - medusa-network

  medusa_redis:
    image: redis:7-alpine
    container_name: medusa_redis
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - medusa-network

  medusa_celery:
    container_name: medusa_celery
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - medusa_db
      - medusa_redis
    networks:
      - medusa-network
    command: ["celery", "-A", "medusa", "worker", "--loglevel=info"]

networks:
  medusa-network:
    external: true

volumes:
  medusa_data:
  static_volume:
  redis_data: