@echo off
echo Stopping PostgreSQL service...
net stop postgresql

echo Cleaning Docker...
docker system prune --force

echo Creating Docker network...
docker network create medusa-network

echo Closing dev and prod Docker containers...
docker compose -f docker-compose.dev.yml down

echo Running Docker Compose for webserver...
docker compose -f docker-compose.dev.yml up --build --remove-orphans