# Generated by Django 5.2 on 2025-05-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-started_at'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='order',
        ),
    ]
