# Generated by Django 5.2 on 2026-01-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_skillsandintroduction_delete_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsandintroduction',
            name='name',
        ),
        migrations.AddField(
            model_name='skillsandintroduction',
            name='title',
            field=models.CharField(default='default', max_length=512),
            preserve_default=False,
        ),
    ]
