# Generated by Django 5.2 on 2026-01-10 10:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_skillsandintroduction_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company_logo',
        ),
        migrations.AddField(
            model_name='experience',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='highlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Highlights'),
        ),
        migrations.AddField(
            model_name='experience',
            name='key_contributions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, default=list, size=None, verbose_name='Key Contributions'),
        ),
        migrations.AddField(
            model_name='experience',
            name='tech_stacks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Tech Stacks'),
        ),
    ]
