# Generated by Django 5.2 on 2026-01-11 05:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_services_started_at_services_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('icon_image', models.URLField(blank=True, max_length=500, null=True)),
                ('icon_image_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order'],
            },
        ),
    ]
