# Generated by Django 5.2 on 2025-06-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_meeting_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
