# Generated by Django 5.2 on 2026-01-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_category_codeblock_comment_contentblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageblock',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
