# Generated by Django 5.2 on 2026-01-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_imageblock_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
