version: '3.9'

services:
  db:
    image: postgres:17
    container_name: medusa_pgdb_replica
    restart: always
    environment:
      POSTGRES_DB: ${PGDB_NAME:-medusa_db}
      POSTGRES_USER: ${PGDB_USER:-medusa_db_owner}
      POSTGRES_PASSWORD: ${PGDB_PASSWORD:-cleanC0de_myth}
    ports:
      - "${PGDB_PORT:-5431}:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - medusa_network

volumes:
  postgres_data:

networks:
  medusa_network:
    external: true
    