# Generated by Django 5.2 on 2025-05-20 20:24

import datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('first_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_name', models.CharField(blank=True, max_length=128, null=True)),
                ('device_type', models.CharField(blank=True, max_length=64, null=True)),
                ('browser', models.CharField(blank=True, max_length=64, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('total_time_spent', models.DurationField(default=datetime.timedelta)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'indexes': [models.Index(fields=['ip_address'], name='base_visito_ip_addr_5289d1_idx'), models.Index(fields=['first_visit'], name='base_visito_first_v_8e9307_idx')],
            },
        ),
    ]
