# Generated by Django 5.2 on 2025-05-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='browser',
            new_name='cookie_id',
        ),
    ]
