# Generated by Django 5.2 on 2025-05-26 15:46

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorizedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(choices=[('skills', 'Skills'), ('services', 'Services'), ('project', 'Project')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vectorized_content',
                'indexes': [models.Index(fields=['collection_type'], name='vectorized__collect_59ffe1_idx'), models.Index(fields=['created_at'], name='vectorized__created_0a148b_idx')],
            },
        ),
    ]
