# Generated by Django 5.2 on 2025-06-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='cookie_id',
        ),
    ]
