# Generated by Django 5.2 on 2025-06-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_visitor_cookie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
